@integration @i4
Feature: The complete two card system
  Both cards working together. A person learns a new concept from the teach
  card, it enters the schedule, and the test card asks about it the next day.
  Obsidian is no longer needed.

  Background:
    Given the desktop application is running
    And a learning directory with three categories
    And "graph/order-security.json" exists

  @e2e @manual
  Scenario: A person learns a concept today and is asked about it tomorrow
    When the person opens the teach card
    Then the first unlearned card in the order file is shown
    When the person reads it and presses next
    Then that card is recorded as learned and due tomorrow
    When the clock advances one day
    And the person opens the test card
    Then that card appears as a fill question

  Scenario: Teaching order follows the dependency graph
    Given "graph/order-security.json" is a topological order of the graph
    When the person presses next repeatedly
    Then cards are shown in that order
    And a card whose prereqs are unlearned shows a prerequisite note
    But pressing next is not blocked

  Scenario: Switching category also records the current card as learned
    When the person switches from security to language
    Then the security card that was displayed is recorded as learned
    And the first unlearned language card is shown

  @llm
  Scenario: Going deeper generates a new level when none exists
    Given the displayed card has no children
    And the network is available
    When the person presses deepen
    Then between 1 and 3 cards are created with level one greater than the parent
    And each has a question file
    And "graph/deps.json" gains an edge from the parent to each new card
    And the first new card is displayed

  Scenario: Going deeper reuses existing children
    Given the displayed card already has two children
    When the person presses deepen
    Then no LLM call is made
    And the first child is displayed

  Scenario: Generated cards obey the same body limit
    When a card is generated by deepen
    Then its body does not exceed 100 words
    And it passes the same validator used by ingest

  @manual
  Scenario: Examples render as markdown with images
    Given a card whose example fence contains a list, bold text and an image
    When the card is displayed
    Then the list and bold text render normally
    And the image is displayed from the assets directory
    And the block is not rendered as preformatted code

  @manual
  Scenario: The daily load hint is shown
    Given the person has learned 4 cards today
    When any card is displayed
    Then the footer shows how many were learned today and roughly how many are due tomorrow

  Scenario: Categories without raw material follow their configuration
    Given the category "peach" has require_raw false and no raw files
    When the person ingests with a topic for that category
    Then cards are generated with source llm and no source_ref
    And the teach card shows the llm source marker on them

  @regression
  Scenario: Desktop review still works as in I3
    When the person opens the test card and answers a question
    Then the schedule advances as in I3
